{{- if and .Values.userCreds.username .Values.userCreds.password .Values.authType.userCreds }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-user-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Namespace }}-cloud-connector
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  username: {{ .Values.userCreds.username | b64enc | quote }}
  password: {{ .Values.userCreds.password | b64enc | quote }}
{{- end }}
