{{- if and .Values.token .Values.authType.tokenAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-token-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Namespace }}-cloud-connector
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  token: {{ .Values.token | b64enc }}
{{- end }}
