---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
{{ include "khulnasoft.labels" . | indent 4 }}
