---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tenantmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-tenantmanager
{{ include "khulnasoft.labels" . | indent 4 }}
{{- if .Values.tenantmanager.service.annotations }}
  annotations:
{{ toYaml .Values.tenantmanager.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.tenantmanager.service.type }}
  selector:
    app: {{ .Release.Name }}-tenantmanager
  ports:
  {{- if eq .Values.platform "k3s"}}
  {{- range $port := .Values.tenantmanager.service.k3sPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      {{- if $port.nodePort }}
      nodePort: {{ $port.nodePort }}
      {{- end }}
      {{- if $port.protocol }}
      protocol: {{ $port.protocol }}
      {{- end }}
  {{- end }}
  {{- else }}
  {{- range $port := .Values.tenantmanager.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      {{- if $port.nodePort }}
      nodePort: {{ $port.nodePort }}
      {{- end }}
      {{- if $port.protocol }}
      protocol: {{ $port.protocol }}
      {{- end }}
  {{- end }}
  {{- end }}
