{{- if not .Values.global.db.external.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-database
    khulnasoft.component: database
{{ include "khulnasoft.labels" . | indent 4 }}
spec:
  type: {{ .Values.global.db.service.type }}
  selector:
    app: {{ .Release.Name }}-database
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-audit-database-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-audit-database
    khulnasoft.component: database-audit
{{ include "khulnasoft.labels" . | indent 4 }}
spec:
  type: {{ .Values.global.db.service.type }}
  selector:
    app: {{ .Release.Name }}-audit-database
  ports:
    - port: 5432
{{- end }}
