{{- if gt (.Values.envoy.replicaCount | default "1" | int) 1 }}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-envoy
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-envoy
    khulnasoft.component: envoy
{{ include "khulnasoft.labels" . | indent 4 }}
spec:
  minAvailable: {{ .Values.envoy.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-envoy
{{- end }}
