{{- if .Values.imageCredentials.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-registry-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    khulnasoft.component: server
{{ include "khulnasoft.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
