{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "server.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    khulnasoft.component: server
{{ include "khulnasoft.labels" . | indent 4 }}
imagePullSecrets:
{{- if .Values.imageCredentials.create }}
- name: {{ .Release.Namespace }}-registry-secret
{{- else }}
- name: {{ .Values.imageCredentials.name }}
{{- end }}
{{- end }}
