{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  name: {{ template "gateway.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    khulnasoft.component: gateway
{{ include "khulnasoft.labels" . | indent 4 }}
imagePullSecrets:
{{- if not .Values.imageCredentials.name }}
{{ template "imageCredentials_name" . }}
{{- end }}
- name: {{ .Values.imageCredentials.name }}
{{- end }}
