{{- if .Values.imageCredentials.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "registrySecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-scanner
    khulnasoft.component: scanner
{{ include "khulnasoft.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
