---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scanner-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-scanner
    khulnasoft.component: scanner
{{ include "khulnasoft.labels" . | indent 4 }}
data:
  SCALOCK_LOG_LEVEL: {{ .Values.logLevel | default "INFO" }}  
  {{- if .Values.cyberCenter.mtls.enabled }}
  AQUA_PRIVATE_KEY: "/opt/khulnasoft/ssl/key.pem"
  AQUA_PUBLIC_KEY: "/opt/khulnasoft/ssl/cert.pem"
  AQUA_ROOT_CA: "/opt/khulnasoft/ssl/ca.pem"
  {{- if .Values.cyberCenter.mtls.rootCA_fileName }}
  OFFLINE_CC_MTLS_ENABLE: "1"
  {{- end }}
  {{- end }}