{{ $relname := .Release.Namespace }}
{{- range $i, $cert := .Values.additionalCerts }}
{{- if $cert.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cert.secretName }}
  namespace: {{ $relname }}
  labels:
    app: {{ .Release.Name }}-scanner
    khulnasoft.component: scanner
{{ include "khulnasoft.labels" . | indent 4 }}
data:
  cert.pem: {{ $cert.certFile }}
{{- end }}
{{- end }}
