{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-scanner
    khulnasoft.component: scanner
{{ include "khulnasoft.labels" . | indent 4 }}
imagePullSecrets:
  - name: {{ template "registrySecret" . }}
{{- end }}
