{{- if .Values.global.imageCredentials.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "registrySecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    role: {{ .Release.Name }}
    app: {{ include "kube-enforcer.fullname" . }}
    khulnasoft.component: kubeenforcer
{{ include "khulnasoft.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}