{{- if not .Values.vaultSecret.enabled }}
{{- if  .Values.khulnasoftSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.khulnasoftSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    role: {{ .Release.Name }}
    app: {{ include "kube-enforcer.fullname" . }}
    khulnasoft.component: kubeenforcer
{{ include "khulnasoft.labels" . | indent 4 }}
type: Opaque
data:
  token: {{ .Values.khulnasoftSecret.kubeEnforcerToken | b64enc }}             # khulnasoft kube enforcer token
{{- end }}
{{- end }}
