{{- if gt (.Values.ke_ReplicaCount | default "1" | int) 1 }}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  labels:
    role: {{ .Release.Name }}
    app: {{ include "kube-enforcer.fullname" . }}
    khulnasoft.component: kubeenforcer
{{ include "khulnasoft.labels" . | indent 4 }}
  name: {{ include "kube-enforcer.fullname" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "kube-enforcer.fullname" . }}
{{- end }}
