---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: {{ .Release.Name }}
    app: {{ include "kube-enforcer.fullname" . }}
    khulnasoft.component: kubeenforcer
{{ include "khulnasoft.labels" . | indent 4 }}
  name: {{ include "kube-enforcer.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      targetPort: 8443
{{- if .Values.kubeEnforcerAdvance.enable }}
      name: envoy
{{- end }}
  selector:
    app: {{ include "kube-enforcer.fullname" . }}
