{{- if .Values.credentials.createSecret  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secretName" . }}
type: Opaque
data:
  USERNAME: {{ .Values.integration.username | toString | b64enc | quote }}
  PASSWORD: {{ .Values.integration.password | toString | b64enc | quote }}
  AQUA_KEY: {{ .Values.credentials.khulnasoft_key | toString | b64enc | quote }}
  AQUA_SECRET: {{ .Values.credentials.khulnasoft_secret | toString | b64enc | quote }}
  {{- if .Values.ssl.enabled }}
  {{- if .Values.ssl.ca }}
  ssl-ca-certificate: {{ .Values.ssl.ca | toString | b64enc }}
  {{- end }}
  {{- if .Values.ssl.cert }}
  ssl-certificate: {{ .Values.ssl.cert | toString | b64enc }}
  {{- end }}
  {{- if .Values.ssl.key }}
  ssl-key: {{ .Values.ssl.key | toString | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}