apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.ke.role.name }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["jobs"]
    verbs: ["create", "delete"]
  - apiGroups: [ "*" ]
    resources: [ "leases" ]
    verbs: [ "get", "list", "create", "update" ]
{{- if eq .Values.platform "openshift" }}
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["create", "delete"]
{{- end }}