---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ke.serviceAccount.name }}
  labels:
    app: {{ .Release.Name }}
    khulnasoft.component: kubeenforcer
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
{{- if not .Values.imageCredentials.name }}
{{ template "imageCredentials_name" . }}
{{- end }}
- name: {{ .Values.imageCredentials.name }}

{{- if (semverCompare ">= 1.19" .Capabilities.KubeVersion.GitVersion) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.starboard.serviceAccount.name }}
  labels:
    app: {{ .Release.Name }}
    khulnasoft.component: starboard-operator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
{{- if not .Values.imageCredentials.name }}
{{ template "imageCredentials_name" . }}
{{- end }}
- name: {{ .Values.imageCredentials.name }}
{{- end }}
