{{- if (semverCompare ">= 1.19" .Capabilities.KubeVersion.GitVersion) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starboard
  namespace: {{ .Release.Namespace }}
data:
  configAuditReports.scanner: Conftest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starboard-conftest-config
  namespace: {{ .Release.Namespace }}
data:
  conftest.imageRef: "{{ .Values.imageCredentials.repositoryUriPrefix }}/{{ .Values.ke.image.repository }}:{{ .Values.ke.image.tag }}"
  conftest.resources.requests.cpu: "{{ .Values.starboard.conftest_resources_requests_cpu }}"
  conftest.resources.requests.memory: "{{ .Values.starboard.conftest_resources_requests_memory }}"
  conftest.resources.limits.cpu: "{{ .Values.starboard.conftest_resources_limits_cpu }}"
  conftest.resources.limits.memory: "{{ .Values.starboard.conftest_resources_limits_memory }}"
{{- end }}
