{{- if .Values.serviceaccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "serviceAccount" . }}
  labels:
    app: {{ .Release.Name }}
{{ include "khulnasoft.labels" . | indent 4 }}
imagePullSecrets:
  - name: {{ template "registrySecret" . }}
{{- end }}
